export const ACTIONS = {
  API: {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_RECEIVED_TOKEN: "LOGIN_RECEIVED_TOKEN",
    LOGIN_ERROR: "LOGIN_ERROR",
    RECOVER_LOCAL_TOKEN: "RECOVER_LOCAL_TOKEN",
  },
};
