export const ACTIONS = {
  API: {
    LOGIN: {
      REQUEST: "REQUEST",
      RECEIVED_TOKEN: "LOGIN_RECEIVED_TOKEN",
      ERROR: "LOGIN_ERROR",
      LOGOUT: "LOGOUT",
      RECOVER_LOCAL_TOKEN: "RECOVER_LOCAL_TOKEN",
    },
    USERS: {
      GET_USERS: "GET_USERS",
      RECEIVE_GET_USERS_DATA: "RECEIVE_GET_USERS_DATA",
    },
  },
};
